name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: 1.11.3.1463
    - name: Build Jar
      run: clojure -T:build jar
